### ISSUE TITLE
Need storyboard

### ISSUE THREAD

**Issue by Logicon211** [Logicon211/LudumDare40#17]

**Comment by seelytaylor** [comment]
[Story_v2.docx](https://github.com/Logicon211/LudumDare40/files/1524201/Story_v2.docx)

**Comment by Logicon211** [comment]
[Story_v2 (1).docx](https://github.com/Logicon211/LudumDare40/files/1524989/Story_v2.1.docx)

**Comment by Logicon211** [comment]
[Story_v2.2.docx](https://github.com/Logicon211/LudumDare40/files/1525068/Story_v2.2.docx)

**Comment by Logicon211** [comment]
[Story_v2.3.docx](https://github.com/Logicon211/LudumDare40/files/1525084/Story_v2.3.docx)

**Comment by Logicon211** [comment]
[Story_v2.4.docx](https://github.com/Logicon211/LudumDare40/files/1525348/Story_v2.4.docx)
