### ISSUE TITLE
Need sounds

### ISSUE THREAD

**Issue by Logicon211** [Logicon211/LudumDare40#19]

**Comment by Logicon211** [comment]
- [ ] Crying babies
- [ ] Tire screeching
- [ ] engine noises
- [ ] throwing noises
- [ ] Put more sounds n stuff in here
- [ ] 
- [ ] In game music
- [ ] into music
- [ ] winning music
- [ ] losing music

**Comment by seelytaylor** [comment]
@Logicon211  victory https://github.com/Logicon211/LudumDare39/blob/master/LudumDare39/Assets/Sounds/Music/Victory-theme.mp3

**Comment by Logicon211** [comment]
- [ ] Dash noise

**Comment by seelytaylor** [comment]
@Logicon211 @MitchellMaclean dash sound 
[dash_sound.zip](https://github.com/Logicon211/LudumDare40/files/1525082/dash_sound.zip)
