### ISSUE TITLE
Need some cars and taxis and trucks

### ISSUE THREAD

**Issue by Logicon211** [Logicon211/LudumDare40#6]

**Comment by seelytaylor** [comment]
farm truck: https://assetstore.unity.com/packages/3d/vehicles/land/industrial-small-truck-free-101483
transport truck: https://assetstore.unity.com/packages/3d/vehicles/land/single-detailed-truck-895
Cars: https://assetstore.unity.com/packages/3d/vehicles/land/simple-cars-pack-97669
